import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import path from "path";
import { fileURLToPath } from "url";

dotenv.config();

const app = express();
const __dirname = path.dirname(fileURLToPath(import.meta.url));

app.use(cors());
app.use(express.json({ limit: "2mb" }));
app.use(express.static(path.join(__dirname, "public")));

const tools = {
  video: { name: "Video Studio", cost: 20 },
    image: { name: "Image Prompt Studio", cost: 5 },
      social: { name: "Social Studio", cost: 3 },
        prompt: { name: "Prompt Builder", cost: 2 },
          cv: { name: "CV Builder", cost: 5 },
            idea: { name: "Business Ideas", cost: 3 }
            };

            function localResult(tool, input, lang) {
              const labels = {
                  ar: ["تحليل الطلب", "النتيجة", "خطوات مقترحة"],
                      en: ["Request analysis", "Result", "Suggested steps"]
                        }[lang] || ["تحليل الطلب", "النتيجة", "خطوات مقترحة"];

                          const name = tools[tool]?.name || "AI Studio";

                            return {
                                title: name,
                                    sections: [
                                          { title: labels[0], text: `تم تحليل طلبك: ${input}` },
                                                {
                                                        title: labels[1],
                                                                text: "هذه نتيجة MVP جاهزة كنقطة بداية. عند إضافة مفتاح مزود الذكاء الاصطناعي في الخادم، سيتم استبدالها بإجابة AI حقيقية."
                                                                      },
                                                                            {
                                                                                    title: labels[2],
                                                                                            text: "حدد الجمهور والهدف والأسلوب، ثم راجع النتيجة قبل النشر."
                                                                                                  }
                                                                                                      ]
                                                                                                        };
                                                                                                        }

                                                                                                        app.get("/api/health", (req, res) => {
                                                                                                          res.json({
                                                                                                              ok: true,
                                                                                                                  service: "Aivora AI",
                                                                                                                      version: "1.0.0"
                                                                                                                        });
                                                                                                                        });

                                                                                                                        app.get("/api/tools", (req, res) => {
                                                                                                                          res.json(tools);
                                                                                                                          });

                                                                                                                          app.post("/api/generate", async (req, res) => {
                                                                                                                            const {
                                                                                                                                tool = "prompt",
                                                                                                                                    input = "",
                                                                                                                                        language = "ar"
                                                                                                                                          } = req.body || {};

                                                                                                                                            if (!input.trim()) {
                                                                                                                                                return res.status(400).json({
                                                                                                                                                      error: "اكتب طلبك أولاً"
                                                                                                                                                          });
                                                                                                                                                            }

                                                                                                                                                              if (!process.env.AI_API_KEY) {
                                                                                                                                                                  return res.json({
                                                                                                                                                                        mode: "demo",
                                                                                                                                                                              credits: tools[tool]?.cost || 2,
                                                                                                                                                                                    result: localResult(tool, input, language)
                                                                                                                                                                                        });
                                                                                                                                                                                          }

                                                                                                                                                                                            try {
                                                                                                                                                                                                const base = (process.env.AI_BASE_URL || "").replace(/\/$/, "");
                                                                                                                                                                                                    const url = base ? `${base}/chat/completions` : "";

                                                                                                                                                                                                        if (!url) {
                                                                                                                                                                                                              return res.json({
                                                                                                                                                                                                                      mode: "demo",
                                                                                                                                                                                                                              credits: tools[tool]?.cost || 2,
                                                                                                                                                                                                                                      result: localResult(tool, input, language)
                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                    const r = await fetch(url, {
                                                                                                                                                                                                                                                          method: "POST",
                                                                                                                                                                                                                                                                headers: {
                                                                                                                                                                                                                                                                        "Content-Type": "application/json",
                                                                                                                                                                                                                                                                                Authorization: `Bearer ${process.env.AI_API_KEY}`
                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                            body: JSON.stringify({
                                                                                                                                                                                                                                                                                                    model: process.env.AI_MODEL || "gpt-4o-mini",
                                                                                                                                                                                                                                                                                                            messages: [
                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                  role: "system",
                                                                                                                                                                                                                                                                                                                                              content: "You are Aivora AI, a concise professional assistant. Return useful structured output."
                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                                                                                                              role: "user",
                                                                                                                                                                                                                                                                                                                                                                                          content: `Tool: ${tools[tool]?.name || tool}\nLanguage: ${language}\nRequest: ${input}`
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                                                    temperature: 0.7
                                                                                                                                                                                                                                                                                                                                                                                                                          })
                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!r.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                        throw new Error(`AI provider error ${r.status}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                const data = await r.json();

                                                                                                                                                                                                                                                                                                                                                                                                                                                    const text =
                                                                                                                                                                                                                                                                                                                                                                                                                                                          data.choices?.[0]?.message?.content || "No result";

                                                                                                                                                                                                                                                                                                                                                                                                                                                              res.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mode: "live",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          credits: tools[tool]?.cost || 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                result: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        title: tools[tool]?.name || tool,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sections: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      title: "AI",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  text
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.status(502).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          error: "تعذر الاتصال بمحرك AI حالياً",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                detail: e.message
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      app.post("/api/checkout", (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!process.env.STRIPE_SECRET_KEY) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return res.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  mode: "demo",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        message: "أضف STRIPE_SECRET_KEY لتفعيل الدفع الحقيقي."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mode: "stripe-ready",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        message: "مفتاح Stripe موجود. اربط إنشاء Checkout Session وWebhook في مرحلة الإنتاج."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          app.get(/.*/, (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.sendFile(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                path.join(__dirname, "public", "index.html")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default app;